### PR TITLE
fixing and refactoring code for OSX support

### PR DESCRIPTION
**Pull request by avatar29A**

### CODE REVIEW

**Comment by avatar29A** [comment]
Hi! I tried to run on OSX your project and I met several problem

- by default app was trying to use OpenGL 2.1
- SDL_PollEvent should be invoke only on Main Thread

It's just a draft PR for discussion. Thanks!

**Comment by drgomesp** [comment]
I have tested this on Linux (`Linux 5.14.18-1-MANJARO`) and it works well.

Would you be able to remove the .idea directory from the commits?

Cheers!

**Comment by avatar29A** [comment]
Ok, I removed from .gitignore `.idea/`. Is that what you meant?

**Comment by drgomesp** [comment]
Yes. Thanks :)

**Pull request merged**
